# Generated by Django 3.2.3 on 2021-07-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('list_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_object', to='auctions.auction_listing')),
            ],
        ),
    ]
