# Generated by Django 3.2.3 on 2021-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
